"""Create document and site tables

Revision ID: 2aa53722ab5a
Revises: 
Create Date: 2026-10-06 20:50:24.390918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2aa53722ab5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('earliest_known_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('has_consent_or_pay_model', sa.Boolean(), nullable=False),
    sa.Column('has_advertisements', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site')),
    sa.UniqueConstraint('host', name=op.f('uq_site_host'))
    )
    op.create_table('document',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('lang_primary', sa.String(), nullable=True),
    sa.Column('lang_ext', sa.String(), nullable=True),
    sa.Column('lang_regconfig', postgresql.REGCONFIG(), nullable=False),
    sa.Column('ip_region', sa.String(), nullable=True),
    sa.Column('crawl_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publication_date_precision', sa.Enum('DAY', 'SECOND', 'MILLISECOND', name='dateprecision'), nullable=True),
    sa.Column('access_date', sa.Date(), nullable=True),
    sa.Column('has_paywall', sa.Boolean(), nullable=False),
    sa.Column('has_login_wall', sa.Boolean(), nullable=False),
    sa.Column('has_generative_ai_content', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(publication_date IS NULL) = (publication_date_precision IS NULL)', name=op.f('ck_document_ck_publication_date_precision_optionality_matches_date')),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_document_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index('ix_document_search', 'document', [sa.literal_column("(setweight(to_tsvector(lang_regconfig, title), 'A') || setweight(to_tsvector(lang_regconfig, body), 'B'))")], unique=False, postgresql_using='gin', postgresql_where=sa.text("lang_regconfig != CAST('simple' AS REGCONFIG)"))
    op.create_index('ix_document_search_simple', 'document', [sa.literal_column("(setweight(to_tsvector('simple', title), 'A') || setweight(to_tsvector('simple', body), 'B'))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_search_simple', table_name='document', postgresql_using='gin')
    op.drop_index('ix_document_search', table_name='document', postgresql_using='gin', postgresql_where=sa.text("lang_regconfig != CAST('simple' AS REGCONFIG)"))
    op.drop_table('document')
    op.drop_table('site')
    # ### end Alembic commands ###
