"""Add document and site tables

Revision ID: 4b1f9c646d8e
Revises: 
Create Date: 2026-10-04 16:03:30.685703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b1f9c646d8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('has_consent_or_pay_model', sa.Boolean(), nullable=False),
    sa.Column('has_advertisements', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('lang_primary', sa.String(), nullable=True),
    sa.Column('lang_ext', sa.String(), nullable=True),
    sa.Column('lang_regconfig', postgresql.REGCONFIG(), nullable=False),
    sa.Column('has_paywalls', sa.Boolean(), nullable=False),
    sa.Column('has_login_walls', sa.Boolean(), nullable=False),
    sa.Column('has_generative_ai_content', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('document_search_idx', 'document', [sa.literal_column("to_tsvector(lang_regconfig, title || ' ' || body)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('document_search_idx', table_name='document', postgresql_using='gin')
    op.drop_table('document')
    op.drop_table('site')
    # ### end Alembic commands ###
