"""Create index for nonlocalised document keyword search

Revision ID: aac23460d1bd
Revises: 4b1f9c646d8e
Create Date: 2026-10-05 19:07:38.670204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac23460d1bd'
down_revision: Union[str, Sequence[str], None] = '4b1f9c646d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('document_search_idx'), table_name='document', postgresql_using='gin')
    op.create_index('ix_document_search', 'document', [sa.literal_column("to_tsvector(lang_regconfig, title || ' ' || body)")], unique=False, postgresql_using='gin', postgresql_where=sa.text("lang_regconfig != CAST('simple' AS REGCONFIG)"))
    op.create_index('ix_document_search_simple', 'document', [sa.literal_column("to_tsvector('simple', title || ' ' || body)")], unique=False, postgresql_using='gin')
    op.create_unique_constraint(op.f('uq_site_host'), 'site', ['host'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_site_host'), 'site', type_='unique')
    op.drop_index('ix_document_search_simple', table_name='document', postgresql_using='gin')
    op.drop_index('ix_document_search', table_name='document', postgresql_using='gin', postgresql_where=sa.text("lang_regconfig != CAST('simple' AS REGCONFIG)"))
    op.create_index(op.f('document_search_idx'), 'document', [sa.literal_column("to_tsvector(lang_regconfig, (title::text || ' '::text) || body::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
